# Site information
title:			Iker's Tech Notes
description: 		A journey through coding, Linux, and everything in between.
author: 		Iker Pedrosa

# Social profiles
github_username:	ikerexxe
linkedin_username:	ikerpedrosa

# Build settings
remote_theme: 		StartBootstrap/startbootstrap-clean-blog-jekyll #jekyll-theme-clean-blog
permalink:		/:categories/:year/:month/:day/:title/
paginate:		10
paginate_path:		"/posts/page:num/"

# Plugins
plugins:
  - jekyll-feed
